---
title: "xcms tutorial"
author: "Chuyao Wang"
date: "`r Sys.Date()`"
output: 
  html_document: 
    number_sections: true # automatic section numbering
    toc: yes # table of content
    toc_depth: 3
    toc_float: true
    smooth_scroll: true
    toc_collapsed: true
    fig_caption: yes
    df_print: kable
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "./html") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(xcms)
library(CAMERA)
library(dplyr)
library(stringr)
```

```{r parallel-setup, eval = TRUE}
#' Set up parallel processing using 2 cores
if (.Platform$OS.type == "unix") {
    register(bpstart(MulticoreParam(2)))
} else {
    register(bpstart(SnowParam(2)))
}
```

```{r serial-setup}
register(SerialParam())
```

# Data import

```{r loadData}
datadir <- "./data/20220824"
file <- list.files(path = datadir, pattern = "^.*\\.mzML$",
                   all.files = TRUE, full.names = TRUE,
                   recursive = FALSE, ignore.case = FALSE,
                   include.dirs = FALSE, no.. = TRUE)
pd <- data.frame(file = basename(file),
                 sample = c("Sample1", "Sample2","Sample3"),
                 group = c("Control","Case","Case"))
data <- readMSData(file, # filenames to load
                   # Stores data; stores sample info into @phenoData@data
                   # More info about each variable: file, injection. sample etc. can be entered in varMetadata
                   pdata = new("NAnnotatedDataFrame", pd), 
                   mode = "onDisk" # Only load metadata into memory and leave the m/z ratio vs intensity peaks on disk
) %>% filterMsLevel(1)
```

```{r viewData}
featureData <- fData(data)

polarity(data) %>% table
msLevel(data) %>% table
```

# Data centroiding

## Chromatogram

```{r chromatogram}
chr_pos <- chromatogram(data %>% filterPolarity(1), aggregationFun = "max")
chr_neg <- chromatogram(data %>% filterPolarity(0), aggregationFun = "max")
```

```{r}
dim(chr_pos)
```

```{r fig.width = 10, fig.height = 5, fig.pos = "h!"}
plot(chr_pos %>% `[[`(1,1))
```

## Centroiding

```{r denoise-and-centroid, results='hide'}
data_cent <- data %>%
      smooth(method = "SavitzkyGolay", halfWindowSize = 2) %>%
      #combineSpectraMovingWindow() %>%
      pickPeaks(refineMz = "descendPeak")

name <- fileNames(data) %>%
  str_remove(".mzML") %>%
  paste("cent",sep = "_") %>%
  paste("mzML",sep = ".")
      
lapply(name, function (z) {
    if (file.exists(z))
        file.remove(z)
}) 
      
writeMSData(data_cent,file=name)
```

```{r XIC, fig.cap= "Profile Mode", fig.width = 10, fig.height = 5, fig.pos = "h!"}
data %>%
  filterFile(file = 1) %>%
  filterPolarity(1) %>%
  filterRt(rt = c(55,65)) %>%
  filterMz(mz = c(116.065,116.075)) %>%
  plot(type = "XIC") 
```

```{r fig.cap= "Cent Mode", fig.width = 10, fig.height = 5, fig.pos = "h!"}
data_cent %>%
  filterFile(file = 1) %>%
  filterPolarity(1) %>%
  filterRt(rt = c(55,65)) %>%
  filterMz(mz = c(116.065,116.075)) %>%
  plot(type = "XIC")
```

```{r proline-before}
data %>%
  filterFile(file = 1) %>%
  filterPolarity(1) %>%
  filterRt(rt = c(55,65)) %>%
  filterMz(mz = c(116.065,116.075)) %>%
  spectra %>%
  `[[`(4) %>%
  MSnbase::plot()
```

```{r proline-after}
data_cent %>%
  filterFile(file = 1) %>%
  filterPolarity(1) %>%
  filterRt(rt = c(55,65)) %>%
  filterMz(mz = c(116.065,116.075)) %>%
  spectra %>%
  `[[`(4) %>%
  MSnbase::plot()
```

# Pre-processing

## Read the centroided data

```{r}
datadir <- "./data/20220824"

file <- list.files(path = datadir, pattern = "cent",
                   all.files = TRUE, full.names = TRUE,
                   recursive = FALSE, ignore.case = FALSE,
                   include.dirs = FALSE, no.. = TRUE)

pd <- data.frame(file = basename(file),
                 sample = c("Sample1", "Sample2","Sample3"),
                 group = c("Control","Case","Case"))

data_cent <- readMSData(file, pdata = new("NAnnotatedDataFrame", pd),
                        mode = "onDisk") 
```

## Peak detection

### With default parameters

```{r}
params <- CentWavePredIsoParam()

chr <- data_cent %>%
  chromatogram(aggregationFun = "max")

res <- findChromPeaks(chr, param = params)
```

### Fine-tune parameters

#### Peak width

Look at the peak width of several peaks to determine a good range

```{r}
data_cent %>%
  filterPolarity(1) %>%
  filterFile(1) %>%
  filterRt(rt = c(50,60)) %>%
  filterMz(mz = c(152,152.1)) %>%
  chromatogram %>%
  MSnbase::plot()
```

> Peak width \> 12 seconds

```{r}
data_cent %>%
  filterPolarity(1) %>%
  filterFile(1) %>%
  filterRt(rt = c(85,100)) %>%
  filterMz(mz = c(136.06,136.07)) %>%
  chromatogram %>%
  MSnbase::plot()
```

> about 6 seconds

```{r}
data_cent %>%
  filterPolarity(1) %>%
  filterFile(1) %>%
  filterRt(rt = c(636,666)) %>%
  filterMz(mz = c(223.16,223.172)) %>%
  chromatogram %>%
  MSnbase::plot()
```

> More than 15 seconds

```{r}
data_cent %>%
  filterFile(file = 1) %>%
  filterPolarity(1) %>%
  filterRt(rt = c(40,100)) %>%
  filterMz(mz = c(116.065,116.075)) %>%
  chromatogram(aggregationFun = "max") %>%
  MSnbase::plot()
```

> More than 15 seconds
>
> Going with range 6-20

```{r}
params <- CentWavePredIsoParam(peakwidth = c(1,200),
                        integrate = 2,
                        ppm = 40)

chr <- data_cent %>%
  # filterFile(file = 1) %>%
  # filterPolarity(1) %>%
  filterRt(rt = c(55,70)) %>%
  filterMz(mz = c(116.065,116.075)) %>%
  chromatogram(aggregationFun = "max")

chr <- findChromPeaks(chr, param = params)
```

```{r}
chromPeaks(chr)
```

```{r}
pro <- data_cent %>%
  # filterFile(file = 1) %>%
  # filterPolarity(1) %>%
  filterRt(rt = c(55,70)) %>%
  filterMz(mz = c(116.065,116.075))

ints_pro <- split(intensity(pro),fromFile(pro))
```
