---
title: "test"
author: "Chuyao Wang"
date: "2022-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(xcms)
library(stringr)
library(gtools)
library(MSnbase)
library(purrr)

data_cent <- function(file) {
  data <- readMSData(file,
                     mode = "onDisk") %>%
    pickPeaks()
  
  fls_new <- fileNames(data) %>%
    str_sub(end=-6) %>%
    paste("cent",sep = "_") %>%
    paste("mzML",sep = ".")
  writeMSData(data, file = fls_new)
}

remove_original <- function() {
  fls <- list.files(path = datadir, pattern = "^.*\\.mzML$",
                    all.files = TRUE, full.names = TRUE,
                    recursive = FALSE, ignore.case = FALSE,
                    include.dirs = FALSE, no.. = TRUE)  %>%
    mixedsort(decreasing = F)
  fls <- fls[!str_detect(fls,"cent")]
  file.remove(fls)
}

get_mz_cn <- function(C,N,H,O,pol) {
  # Get the mz ratios of a C and N isotope labeled compound
  # specify the number of c, n, h, o atoms
  # specify polarity for +1 charge or -1 charge
  
  m.c12 <- 12
  m.c13 <- 13.003355
  m.h <- 1.007825
  m.n14 <- 14.003074
  m.n15 <- 15.000109
  m.o16 <- 15.994915
  m.o17 <- 16.999131
  m.o18 <- 17.999159
  m.p <- 1.00727646677 # ex mass of proton
  
  b <- c(m.c12,m.c13,m.n14,m.n15,m.h,m.o16)
  
  a <- matrix(
    c(
      rep(0:C,each=N+1),
      rep(C:0,each=N+1),
      rep(0:N,times=C+1),
      rep(N:0,times=C+1),
      rep(H,times=(C+1)*(N+1)),
      rep(O,times=(C+1)*(N+1))
    ),
    ncol = length(b)
  )
  
  mz <- (a %*% b + pol*m.p) %>%
    matrix(nrow = N+1, ncol = C+1) %>%
    as.data.frame(
      row.names = paste("[15]N",N:0,sep = "")
    )
  
  colnames(mz) <- paste("[13]C",C:0,sep = "")
  
  return(mz)
}

get_ppm_range <- function(x,ppm) {
  return(x*c(1-ppm*1e-6,1+ppm*1e-6))
}

rsd <- function(x) {sd(x)/mean(x)} # relative standard deviation
```

```{r addFunc}
remove_zeros <- function(x) {
  x <- x[!x==0]
  return(x)
}
```


```{r setVariables}
datadir = "./data/20221012" # Edit data directory
ppm = 5
rt_range = c(2.3,3.0)
C = 6
H = 14
N = 2
O = 2
pol = 1 # -1 for neg mode
unlabeled = NA # If "C" or "N" is unlabeled, or NA if C and N are both labeled
centroidData = TRUE # use centroided data or not; using centroided data takes the max intensity in a mz dimension cluster; using original data takes the sum intensity in a mz dimension cluster
parallel = FALSE # Use biocparallel or not; not recommended

register(SerialParam())

fls <- list.files(path = datadir, pattern = "^.*\\.mzML$",
                  all.files = TRUE, full.names = TRUE,
                  recursive = FALSE, ignore.case = FALSE,
                  include.dirs = FALSE, no.. = TRUE)  %>%
  mixedsort(decreasing = F)

fls_cent <- fls[str_detect(fls,"cent")]

fls <- fls[!str_detect(fls,"cent")]
```

```{r readData}
data <- readMSData(fls, mode = "onDisk")
data_cent <- readMSData(fls_cent, mode = "onDisk")
```

```{r getMzs}
mzs <- get_mz_cn(C=C,H=H,N=N,O=O,pol=pol) # mz ratio
label <- sapply(colnames(mzs), function(x) {
  sapply(rownames(mzs), function(y) {
    paste(x,y,sep="_")
  })
})
mzs_vec <- as.vector(as.matrix(mzs))

```

```{r getChr}
chr <- data %>%
  filterMz(mz = get_ppm_range(x=max(mzs),ppm=ppm)) %>%
  filterRt(rt = 60*rt_range) %>%
  chromatogram(aggregationFun = "max", missing = 0)

chr_cent <- data_cent %>%
  filterMz(mz = get_ppm_range(x=max(mzs),ppm=ppm)) %>%
  filterRt(rt = 60*rt_range) %>%
  chromatogram(aggregationFun = "max", missing = 0)
```

```{r getInts_uncent_mean}
meanIntensity = TRUE # compute intensities from max spectra or mean of half-width spectrum
mz_int <- lapply(seq_along(fls), function(f) {
    print(paste("Processing File",f))
    res_uncent_mean <- list()
    
    # Get acquisition number(s)
    if (meanIntensity == TRUE) {
      ints <- intensity(chr[1,f])
      acNum <- ints[ints >= (0.5*max(ints))] %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    } else if (meanIntensity == FALSE) {
      acNum <- intensity(chr[1,f]) %>%
        which.max %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    }
    
    # Getting spectrum
    sp <- data %>%
      filterFile(f) %>%
      filterAcquisitionNum(n = acNum)
    
    for (i in seq_along(mzs_vec)) {
      x <- mzs_vec[i]
      
      # Matching mzs
      matched <- sp %>%
        filterMz(mz = get_ppm_range(x = x,ppm = ppm))
      
      # Obtain mz intensity pair
      vals <- c(mz(matched) %>% unlist %>% remove_zeros %>% mean,
                intensity(matched) %>% sapply(sum) %>% remove_zeros %>% mean)
      
      # Output result
      if (is.na(sum(vals))) {
        res_uncent_mean[[i]] <- c(x,0)
      } else {
        res_uncent_mean[[i]] <- vals
      }
    }
    
    return(res_uncent_mean)

  })
```

```{r getInts_uncent_max}
meanIntensity = FALSE # compute intensities from max spectra or mean of half-width spectrum
mz_int_uncent_max <- lapply(seq_along(fls), function(f) {
    print(paste("Processing File",f))
    res_uncent_max <- list()
    
    # Get acquisition number(s)
    if (meanIntensity == TRUE) {
      ints <- intensity(chr[1,f])
      acNum <- ints[ints >= (0.5*max(ints))] %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    } else if (meanIntensity == FALSE) {
      acNum <- intensity(chr[1,f]) %>%
        which.max %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    }
    
    # Getting spectrum
    sp <- data %>%
      filterFile(f) %>%
      filterAcquisitionNum(n = acNum)
    
    for (i in seq_along(mzs_vec)) {
      x <- mzs_vec[i]
      
      # Matching mzs
      matched <- sp %>%
        filterMz(mz = get_ppm_range(x = x,ppm = ppm))
      
      # Obtain mz intensity pair
      vals <- c(mz(matched) %>% sapply(mean) %>% remove_zeros %>% mean,
                intensity(matched) %>% sapply(sum) %>% remove_zeros %>% mean)
      
      # Output result
      if (is.na(sum(vals))) {
        res_uncent_max[[i]] <- c(x,0)
      } else {
        res_uncent_max[[i]] <- vals
      }
    }
    
    return(res_uncent_max)
  })

```

```{r getInts_cent_mean}
meanIntensity = TRUE # compute intensities from max spectra or mean of half-width spectrum
mz_int_cent_mean <- lapply(seq_along(fls), function(f) {
    print(paste("Processing File",f))
    res_uncent_mean <- list()
    
    # Get acquisition number(s)
    if (meanIntensity == TRUE) {
      ints <- intensity(chr_cent[1,f])
      acNum <- ints[ints >= (0.5*max(ints))] %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    } else if (meanIntensity == FALSE) {
      acNum <- intensity(chr_cent[1,f]) %>%
        which.max %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    }
    
    # Getting spectrum
    sp <- data_cent %>%
      filterFile(f) %>%
      filterAcquisitionNum(n = acNum)
    
    for (i in seq_along(mzs_vec)) {
      x <- mzs_vec[i]
      
      # Matching mzs
      matched <- sp %>%
        filterMz(mz = get_ppm_range(x = x,ppm = ppm))
      
      # Obtain mz intensity pair
      vals <- c(mz(matched) %>% unlist %>% remove_zeros %>% mean,
                intensity(matched) %>% sapply(sum) %>% remove_zeros %>% mean)
      
      # Output result
      if (is.na(sum(vals))) {
        res_uncent_mean[[i]] <- c(x,0)
      } else {
        res_uncent_mean[[i]] <- vals
      }
    }
    
    return(res_uncent_mean)

  })
```

```{r getInts_cent_mean}
meanIntensity = FALSE # compute intensities from max spectra or mean of half-width spectrum
mz_int_cent_max <- lapply(seq_along(fls), function(f) {
    print(paste("Processing File",f))
    res_uncent_mean <- list()
    
    # Get acquisition number(s)
    if (meanIntensity == TRUE) {
      ints <- intensity(chr_cent[1,f])
      acNum <- ints[ints >= (0.5*max(ints))] %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    } else if (meanIntensity == FALSE) {
      acNum <- intensity(chr_cent[1,f]) %>%
        which.max %>%
        names %>%
        str_extract("(?<=S)[:digit:]+") %>%
        as.integer
    }
    
    # Getting spectrum
    sp <- data_cent %>%
      filterFile(f) %>%
      filterAcquisitionNum(n = acNum)
    
    for (i in seq_along(mzs_vec)) {
      x <- mzs_vec[i]
      
      # Matching mzs
      matched <- sp %>%
        filterMz(mz = get_ppm_range(x = x,ppm = ppm))
      
      # Obtain mz intensity pair
      vals <- c(mz(matched) %>% unlist %>% remove_zeros %>% mean,
                intensity(matched) %>% sapply(sum) %>% remove_zeros %>% mean)
      
      # Output result
      if (is.na(sum(vals))) {
        res_uncent_mean[[i]] <- c(x,0)
      } else {
        res_uncent_mean[[i]] <- vals
      }
    }
    
    return(res_uncent_mean)

  })
```